[package]
name = "pulumi-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
prost = "0.14.3"
rust2go = "0.4.2"
pulumi_gestalt_schema = "0.0.7"
pulumi_gestalt_generator = "0.0.7"
prettyplease = "0.2.37"
syn = "2.0.117"
codegen = "0.3.0"
rootcause = "0.12.1"
#rust2go.workspace = true

#[workspace]
#rust2go = "0.4.3"

[build-dependencies]
prost-build = "0.14.3"
