// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pcl.proto

package schemapcl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_ADD                   Operation = 0
	Operation_DIVIDE                Operation = 1
	Operation_EQUAL                 Operation = 2
	Operation_GREATER_THAN          Operation = 3
	Operation_GREATER_THAN_OR_EQUAL Operation = 4
	Operation_LESS_THAN             Operation = 5
	Operation_LESS_THAN_OR_EQUAL    Operation = 6
	Operation_LOGICAL_AND           Operation = 7
	Operation_LOGICAL_OR            Operation = 8
	Operation_MODULO                Operation = 9
	Operation_MULTIPLY              Operation = 10
	Operation_NOT_EQUAL             Operation = 11
	Operation_SUBTRACT              Operation = 12
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "ADD",
		1:  "DIVIDE",
		2:  "EQUAL",
		3:  "GREATER_THAN",
		4:  "GREATER_THAN_OR_EQUAL",
		5:  "LESS_THAN",
		6:  "LESS_THAN_OR_EQUAL",
		7:  "LOGICAL_AND",
		8:  "LOGICAL_OR",
		9:  "MODULO",
		10: "MULTIPLY",
		11: "NOT_EQUAL",
		12: "SUBTRACT",
	}
	Operation_value = map[string]int32{
		"ADD":                   0,
		"DIVIDE":                1,
		"EQUAL":                 2,
		"GREATER_THAN":          3,
		"GREATER_THAN_OR_EQUAL": 4,
		"LESS_THAN":             5,
		"LESS_THAN_OR_EQUAL":    6,
		"LOGICAL_AND":           7,
		"LOGICAL_OR":            8,
		"MODULO":                9,
		"MULTIPLY":              10,
		"NOT_EQUAL":             11,
		"SUBTRACT":              12,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_pcl_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_pcl_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{0}
}

type PclProtobufProgram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Plugins       []*PluginReference     `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PclProtobufProgram) Reset() {
	*x = PclProtobufProgram{}
	mi := &file_pcl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PclProtobufProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PclProtobufProgram) ProtoMessage() {}

func (x *PclProtobufProgram) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PclProtobufProgram.ProtoReflect.Descriptor instead.
func (*PclProtobufProgram) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{0}
}

func (x *PclProtobufProgram) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PclProtobufProgram) GetPlugins() []*PluginReference {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type PluginReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginReference) Reset() {
	*x = PluginReference{}
	mi := &file_pcl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginReference) ProtoMessage() {}

func (x *PluginReference) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginReference.ProtoReflect.Descriptor instead.
func (*PluginReference) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{1}
}

func (x *PluginReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginReference) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Node_Resource
	//	*Node_LocalVariable
	//	*Node_ConfigVariable
	//	*Node_OutputVariable
	Value         isNode_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pcl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetValue() isNode_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Node) GetResource() *Resource {
	if x != nil {
		if x, ok := x.Value.(*Node_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *Node) GetLocalVariable() *LocalVariable {
	if x != nil {
		if x, ok := x.Value.(*Node_LocalVariable); ok {
			return x.LocalVariable
		}
	}
	return nil
}

func (x *Node) GetConfigVariable() *ConfigVariable {
	if x != nil {
		if x, ok := x.Value.(*Node_ConfigVariable); ok {
			return x.ConfigVariable
		}
	}
	return nil
}

func (x *Node) GetOutputVariable() *OutputVariable {
	if x != nil {
		if x, ok := x.Value.(*Node_OutputVariable); ok {
			return x.OutputVariable
		}
	}
	return nil
}

type isNode_Value interface {
	isNode_Value()
}

type Node_Resource struct {
	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3,oneof"`
}

type Node_LocalVariable struct {
	LocalVariable *LocalVariable `protobuf:"bytes,2,opt,name=localVariable,proto3,oneof"`
}

type Node_ConfigVariable struct {
	ConfigVariable *ConfigVariable `protobuf:"bytes,3,opt,name=configVariable,proto3,oneof"`
}

type Node_OutputVariable struct {
	OutputVariable *OutputVariable `protobuf:"bytes,4,opt,name=outputVariable,proto3,oneof"`
}

func (*Node_Resource) isNode_Value() {}

func (*Node_LocalVariable) isNode_Value() {}

func (*Node_ConfigVariable) isNode_Value() {}

func (*Node_OutputVariable) isNode_Value() {}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalName   string                 `protobuf:"bytes,2,opt,name=logicalName,proto3" json:"logicalName,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Inputs        []*ResourceInput       `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Options       *ResourceOptions       `protobuf:"bytes,5,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pcl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetLogicalName() string {
	if x != nil {
		return x.LogicalName
	}
	return ""
}

func (x *Resource) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Resource) GetInputs() []*ResourceInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Resource) GetOptions() *ResourceOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ResourceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Expression            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInput) Reset() {
	*x = ResourceInput{}
	mi := &file_pcl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInput) ProtoMessage() {}

func (x *ResourceInput) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInput.ProtoReflect.Descriptor instead.
func (*ResourceInput) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceInput) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResourceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DependsOn     *Expression            `protobuf:"bytes,1,opt,name=dependsOn,proto3,oneof" json:"dependsOn,omitempty"`
	Protect       *Expression            `protobuf:"bytes,2,opt,name=protect,proto3,oneof" json:"protect,omitempty"`
	Parent        *Expression            `protobuf:"bytes,3,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	IgnoreChanges *Expression            `protobuf:"bytes,4,opt,name=ignoreChanges,proto3,oneof" json:"ignoreChanges,omitempty"`
	Provider      *Expression            `protobuf:"bytes,5,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Version       *Expression            `protobuf:"bytes,6,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Range         *Expression            `protobuf:"bytes,7,opt,name=range,proto3,oneof" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceOptions) Reset() {
	*x = ResourceOptions{}
	mi := &file_pcl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOptions) ProtoMessage() {}

func (x *ResourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceOptions.ProtoReflect.Descriptor instead.
func (*ResourceOptions) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceOptions) GetDependsOn() *Expression {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ResourceOptions) GetProtect() *Expression {
	if x != nil {
		return x.Protect
	}
	return nil
}

func (x *ResourceOptions) GetParent() *Expression {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ResourceOptions) GetIgnoreChanges() *Expression {
	if x != nil {
		return x.IgnoreChanges
	}
	return nil
}

func (x *ResourceOptions) GetProvider() *Expression {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ResourceOptions) GetVersion() *Expression {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ResourceOptions) GetRange() *Expression {
	if x != nil {
		return x.Range
	}
	return nil
}

type LocalVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalName   string                 `protobuf:"bytes,2,opt,name=logicalName,proto3" json:"logicalName,omitempty"`
	Value         *Expression            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalVariable) Reset() {
	*x = LocalVariable{}
	mi := &file_pcl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalVariable) ProtoMessage() {}

func (x *LocalVariable) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalVariable.ProtoReflect.Descriptor instead.
func (*LocalVariable) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{6}
}

func (x *LocalVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalVariable) GetLogicalName() string {
	if x != nil {
		return x.LogicalName
	}
	return ""
}

func (x *LocalVariable) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConfigVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalName   string                 `protobuf:"bytes,2,opt,name=logicalName,proto3" json:"logicalName,omitempty"`
	ConfigType    *ConfigType            `protobuf:"bytes,3,opt,name=configType,proto3" json:"configType,omitempty"`
	DefaultValue  *Expression            `protobuf:"bytes,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVariable) Reset() {
	*x = ConfigVariable{}
	mi := &file_pcl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVariable) ProtoMessage() {}

func (x *ConfigVariable) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVariable.ProtoReflect.Descriptor instead.
func (*ConfigVariable) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigVariable) GetLogicalName() string {
	if x != nil {
		return x.LogicalName
	}
	return ""
}

func (x *ConfigVariable) GetConfigType() *ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return nil
}

func (x *ConfigVariable) GetDefaultValue() *Expression {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

type ConfigType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigType_StringType
	//	*ConfigType_NumberType
	//	*ConfigType_IntType
	//	*ConfigType_BoolType
	//	*ConfigType_ListType
	//	*ConfigType_MapType
	Value         isConfigType_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigType) Reset() {
	*x = ConfigType{}
	mi := &file_pcl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigType) ProtoMessage() {}

func (x *ConfigType) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigType.ProtoReflect.Descriptor instead.
func (*ConfigType) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigType) GetValue() isConfigType_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigType) GetStringType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_StringType); ok {
			return x.StringType
		}
	}
	return nil
}

func (x *ConfigType) GetNumberType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_NumberType); ok {
			return x.NumberType
		}
	}
	return nil
}

func (x *ConfigType) GetIntType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_IntType); ok {
			return x.IntType
		}
	}
	return nil
}

func (x *ConfigType) GetBoolType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_BoolType); ok {
			return x.BoolType
		}
	}
	return nil
}

func (x *ConfigType) GetListType() *ConfigType {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_ListType); ok {
			return x.ListType
		}
	}
	return nil
}

func (x *ConfigType) GetMapType() *ConfigType {
	if x != nil {
		if x, ok := x.Value.(*ConfigType_MapType); ok {
			return x.MapType
		}
	}
	return nil
}

type isConfigType_Value interface {
	isConfigType_Value()
}

type ConfigType_StringType struct {
	StringType *Empty `protobuf:"bytes,1,opt,name=stringType,proto3,oneof"`
}

type ConfigType_NumberType struct {
	NumberType *Empty `protobuf:"bytes,2,opt,name=numberType,proto3,oneof"`
}

type ConfigType_IntType struct {
	IntType *Empty `protobuf:"bytes,3,opt,name=intType,proto3,oneof"`
}

type ConfigType_BoolType struct {
	BoolType *Empty `protobuf:"bytes,4,opt,name=boolType,proto3,oneof"`
}

type ConfigType_ListType struct {
	ListType *ConfigType `protobuf:"bytes,5,opt,name=listType,proto3,oneof"`
}

type ConfigType_MapType struct {
	MapType *ConfigType `protobuf:"bytes,6,opt,name=mapType,proto3,oneof"`
}

func (*ConfigType_StringType) isConfigType_Value() {}

func (*ConfigType_NumberType) isConfigType_Value() {}

func (*ConfigType_IntType) isConfigType_Value() {}

func (*ConfigType_BoolType) isConfigType_Value() {}

func (*ConfigType_ListType) isConfigType_Value() {}

func (*ConfigType_MapType) isConfigType_Value() {}

type OutputVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalName   string                 `protobuf:"bytes,2,opt,name=logicalName,proto3" json:"logicalName,omitempty"`
	Value         *Expression            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputVariable) Reset() {
	*x = OutputVariable{}
	mi := &file_pcl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputVariable) ProtoMessage() {}

func (x *OutputVariable) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputVariable.ProtoReflect.Descriptor instead.
func (*OutputVariable) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{9}
}

func (x *OutputVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputVariable) GetLogicalName() string {
	if x != nil {
		return x.LogicalName
	}
	return ""
}

func (x *OutputVariable) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Expression_LiteralValueExpression
	//	*Expression_TemplateExpression
	//	*Expression_IndexExpression
	//	*Expression_ObjectConsExpression
	//	*Expression_TupleConsExpression
	//	*Expression_FunctionCallExpression
	//	*Expression_RelativeTraversalExpression
	//	*Expression_ScopeTraversalExpression
	//	*Expression_AnonymousFunctionExpression
	//	*Expression_ConditionalExpression
	//	*Expression_BinaryOpExpression
	//	*Expression_UnaryOpExpression
	Value         isExpression_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_pcl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{10}
}

func (x *Expression) GetValue() isExpression_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Expression) GetLiteralValueExpression() *LiteralValueExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_LiteralValueExpression); ok {
			return x.LiteralValueExpression
		}
	}
	return nil
}

func (x *Expression) GetTemplateExpression() *TemplateExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_TemplateExpression); ok {
			return x.TemplateExpression
		}
	}
	return nil
}

func (x *Expression) GetIndexExpression() *IndexExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_IndexExpression); ok {
			return x.IndexExpression
		}
	}
	return nil
}

func (x *Expression) GetObjectConsExpression() *ObjectConsExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_ObjectConsExpression); ok {
			return x.ObjectConsExpression
		}
	}
	return nil
}

func (x *Expression) GetTupleConsExpression() *TupleConsExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_TupleConsExpression); ok {
			return x.TupleConsExpression
		}
	}
	return nil
}

func (x *Expression) GetFunctionCallExpression() *FunctionCallExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_FunctionCallExpression); ok {
			return x.FunctionCallExpression
		}
	}
	return nil
}

func (x *Expression) GetRelativeTraversalExpression() *RelativeTraversalExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_RelativeTraversalExpression); ok {
			return x.RelativeTraversalExpression
		}
	}
	return nil
}

func (x *Expression) GetScopeTraversalExpression() *ScopeTraversalExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_ScopeTraversalExpression); ok {
			return x.ScopeTraversalExpression
		}
	}
	return nil
}

func (x *Expression) GetAnonymousFunctionExpression() *AnonymousFunctionExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_AnonymousFunctionExpression); ok {
			return x.AnonymousFunctionExpression
		}
	}
	return nil
}

func (x *Expression) GetConditionalExpression() *ConditionalExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_ConditionalExpression); ok {
			return x.ConditionalExpression
		}
	}
	return nil
}

func (x *Expression) GetBinaryOpExpression() *BinaryOpExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_BinaryOpExpression); ok {
			return x.BinaryOpExpression
		}
	}
	return nil
}

func (x *Expression) GetUnaryOpExpression() *UnaryOpExpression {
	if x != nil {
		if x, ok := x.Value.(*Expression_UnaryOpExpression); ok {
			return x.UnaryOpExpression
		}
	}
	return nil
}

type isExpression_Value interface {
	isExpression_Value()
}

type Expression_LiteralValueExpression struct {
	LiteralValueExpression *LiteralValueExpression `protobuf:"bytes,1,opt,name=literalValueExpression,proto3,oneof"`
}

type Expression_TemplateExpression struct {
	TemplateExpression *TemplateExpression `protobuf:"bytes,2,opt,name=templateExpression,proto3,oneof"`
}

type Expression_IndexExpression struct {
	IndexExpression *IndexExpression `protobuf:"bytes,3,opt,name=indexExpression,proto3,oneof"`
}

type Expression_ObjectConsExpression struct {
	ObjectConsExpression *ObjectConsExpression `protobuf:"bytes,4,opt,name=objectConsExpression,proto3,oneof"`
}

type Expression_TupleConsExpression struct {
	TupleConsExpression *TupleConsExpression `protobuf:"bytes,5,opt,name=tupleConsExpression,proto3,oneof"`
}

type Expression_FunctionCallExpression struct {
	FunctionCallExpression *FunctionCallExpression `protobuf:"bytes,6,opt,name=functionCallExpression,proto3,oneof"`
}

type Expression_RelativeTraversalExpression struct {
	RelativeTraversalExpression *RelativeTraversalExpression `protobuf:"bytes,7,opt,name=relativeTraversalExpression,proto3,oneof"`
}

type Expression_ScopeTraversalExpression struct {
	ScopeTraversalExpression *ScopeTraversalExpression `protobuf:"bytes,8,opt,name=scopeTraversalExpression,proto3,oneof"`
}

type Expression_AnonymousFunctionExpression struct {
	AnonymousFunctionExpression *AnonymousFunctionExpression `protobuf:"bytes,9,opt,name=anonymousFunctionExpression,proto3,oneof"`
}

type Expression_ConditionalExpression struct {
	ConditionalExpression *ConditionalExpression `protobuf:"bytes,10,opt,name=conditionalExpression,proto3,oneof"`
}

type Expression_BinaryOpExpression struct {
	BinaryOpExpression *BinaryOpExpression `protobuf:"bytes,11,opt,name=binaryOpExpression,proto3,oneof"`
}

type Expression_UnaryOpExpression struct {
	UnaryOpExpression *UnaryOpExpression `protobuf:"bytes,12,opt,name=unaryOpExpression,proto3,oneof"`
}

func (*Expression_LiteralValueExpression) isExpression_Value() {}

func (*Expression_TemplateExpression) isExpression_Value() {}

func (*Expression_IndexExpression) isExpression_Value() {}

func (*Expression_ObjectConsExpression) isExpression_Value() {}

func (*Expression_TupleConsExpression) isExpression_Value() {}

func (*Expression_FunctionCallExpression) isExpression_Value() {}

func (*Expression_RelativeTraversalExpression) isExpression_Value() {}

func (*Expression_ScopeTraversalExpression) isExpression_Value() {}

func (*Expression_AnonymousFunctionExpression) isExpression_Value() {}

func (*Expression_ConditionalExpression) isExpression_Value() {}

func (*Expression_BinaryOpExpression) isExpression_Value() {}

func (*Expression_UnaryOpExpression) isExpression_Value() {}

type LiteralValueExpression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*LiteralValueExpression_UnknownValue
	//	*LiteralValueExpression_StringValue
	//	*LiteralValueExpression_NumberValue
	//	*LiteralValueExpression_BoolValue
	Value         isLiteralValueExpression_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiteralValueExpression) Reset() {
	*x = LiteralValueExpression{}
	mi := &file_pcl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiteralValueExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiteralValueExpression) ProtoMessage() {}

func (x *LiteralValueExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiteralValueExpression.ProtoReflect.Descriptor instead.
func (*LiteralValueExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{11}
}

func (x *LiteralValueExpression) GetValue() isLiteralValueExpression_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LiteralValueExpression) GetUnknownValue() bool {
	if x != nil {
		if x, ok := x.Value.(*LiteralValueExpression_UnknownValue); ok {
			return x.UnknownValue
		}
	}
	return false
}

func (x *LiteralValueExpression) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*LiteralValueExpression_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *LiteralValueExpression) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*LiteralValueExpression_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *LiteralValueExpression) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*LiteralValueExpression_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isLiteralValueExpression_Value interface {
	isLiteralValueExpression_Value()
}

type LiteralValueExpression_UnknownValue struct {
	UnknownValue bool `protobuf:"varint,1,opt,name=unknownValue,proto3,oneof"`
}

type LiteralValueExpression_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type LiteralValueExpression_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=numberValue,proto3,oneof"`
}

type LiteralValueExpression_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=boolValue,proto3,oneof"`
}

func (*LiteralValueExpression_UnknownValue) isLiteralValueExpression_Value() {}

func (*LiteralValueExpression_StringValue) isLiteralValueExpression_Value() {}

func (*LiteralValueExpression_NumberValue) isLiteralValueExpression_Value() {}

func (*LiteralValueExpression_BoolValue) isLiteralValueExpression_Value() {}

type TemplateExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Expression          `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateExpression) Reset() {
	*x = TemplateExpression{}
	mi := &file_pcl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateExpression) ProtoMessage() {}

func (x *TemplateExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateExpression.ProtoReflect.Descriptor instead.
func (*TemplateExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{12}
}

func (x *TemplateExpression) GetParts() []*Expression {
	if x != nil {
		return x.Parts
	}
	return nil
}

type IndexExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Expression            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           *Expression            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexExpression) Reset() {
	*x = IndexExpression{}
	mi := &file_pcl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexExpression) ProtoMessage() {}

func (x *IndexExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexExpression.ProtoReflect.Descriptor instead.
func (*IndexExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{13}
}

func (x *IndexExpression) GetCollection() *Expression {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *IndexExpression) GetKey() *Expression {
	if x != nil {
		return x.Key
	}
	return nil
}

type ObjectConsExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    map[string]*Expression `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectConsExpression) Reset() {
	*x = ObjectConsExpression{}
	mi := &file_pcl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectConsExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectConsExpression) ProtoMessage() {}

func (x *ObjectConsExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectConsExpression.ProtoReflect.Descriptor instead.
func (*ObjectConsExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{14}
}

func (x *ObjectConsExpression) GetProperties() map[string]*Expression {
	if x != nil {
		return x.Properties
	}
	return nil
}

type TupleConsExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Expression          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleConsExpression) Reset() {
	*x = TupleConsExpression{}
	mi := &file_pcl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleConsExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleConsExpression) ProtoMessage() {}

func (x *TupleConsExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleConsExpression.ProtoReflect.Descriptor instead.
func (*TupleConsExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{15}
}

func (x *TupleConsExpression) GetItems() []*Expression {
	if x != nil {
		return x.Items
	}
	return nil
}

type FunctionCallExpression struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []*FunctionCallArgument `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallExpression) Reset() {
	*x = FunctionCallExpression{}
	mi := &file_pcl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallExpression) ProtoMessage() {}

func (x *FunctionCallExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallExpression.ProtoReflect.Descriptor instead.
func (*FunctionCallExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{16}
}

func (x *FunctionCallExpression) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallExpression) GetArgs() []*FunctionCallArgument {
	if x != nil {
		return x.Args
	}
	return nil
}

type FunctionCallArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Expression            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallArgument) Reset() {
	*x = FunctionCallArgument{}
	mi := &file_pcl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallArgument) ProtoMessage() {}

func (x *FunctionCallArgument) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallArgument.ProtoReflect.Descriptor instead.
func (*FunctionCallArgument) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{17}
}

func (x *FunctionCallArgument) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FunctionCallArgument) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Type_BoolType
	//	*Type_IntType
	//	*Type_NumberType
	//	*Type_StringType
	//	*Type_Composite
	//	*Type_OutputType
	Value         isType_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_pcl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{18}
}

func (x *Type) GetValue() isType_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Type) GetBoolType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*Type_BoolType); ok {
			return x.BoolType
		}
	}
	return nil
}

func (x *Type) GetIntType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*Type_IntType); ok {
			return x.IntType
		}
	}
	return nil
}

func (x *Type) GetNumberType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*Type_NumberType); ok {
			return x.NumberType
		}
	}
	return nil
}

func (x *Type) GetStringType() *Empty {
	if x != nil {
		if x, ok := x.Value.(*Type_StringType); ok {
			return x.StringType
		}
	}
	return nil
}

func (x *Type) GetComposite() *Empty {
	if x != nil {
		if x, ok := x.Value.(*Type_Composite); ok {
			return x.Composite
		}
	}
	return nil
}

func (x *Type) GetOutputType() *Type {
	if x != nil {
		if x, ok := x.Value.(*Type_OutputType); ok {
			return x.OutputType
		}
	}
	return nil
}

type isType_Value interface {
	isType_Value()
}

type Type_BoolType struct {
	BoolType *Empty `protobuf:"bytes,1,opt,name=boolType,proto3,oneof"`
}

type Type_IntType struct {
	IntType *Empty `protobuf:"bytes,2,opt,name=intType,proto3,oneof"`
}

type Type_NumberType struct {
	NumberType *Empty `protobuf:"bytes,3,opt,name=numberType,proto3,oneof"`
}

type Type_StringType struct {
	StringType *Empty `protobuf:"bytes,4,opt,name=stringType,proto3,oneof"`
}

type Type_Composite struct {
	Composite *Empty `protobuf:"bytes,5,opt,name=composite,proto3,oneof"`
}

type Type_OutputType struct {
	OutputType *Type `protobuf:"bytes,6,opt,name=outputType,proto3,oneof"`
}

func (*Type_BoolType) isType_Value() {}

func (*Type_IntType) isType_Value() {}

func (*Type_NumberType) isType_Value() {}

func (*Type_StringType) isType_Value() {}

func (*Type_Composite) isType_Value() {}

func (*Type_OutputType) isType_Value() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pcl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{19}
}

type RelativeTraversalExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Expression            `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Traversal     *Traversal             `protobuf:"bytes,2,opt,name=traversal,proto3" json:"traversal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativeTraversalExpression) Reset() {
	*x = RelativeTraversalExpression{}
	mi := &file_pcl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeTraversalExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeTraversalExpression) ProtoMessage() {}

func (x *RelativeTraversalExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeTraversalExpression.ProtoReflect.Descriptor instead.
func (*RelativeTraversalExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{20}
}

func (x *RelativeTraversalExpression) GetSource() *Expression {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RelativeTraversalExpression) GetTraversal() *Traversal {
	if x != nil {
		return x.Traversal
	}
	return nil
}

type ScopeTraversalExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=rootName,proto3" json:"rootName,omitempty"`
	Traversal     *Traversal             `protobuf:"bytes,2,opt,name=traversal,proto3" json:"traversal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeTraversalExpression) Reset() {
	*x = ScopeTraversalExpression{}
	mi := &file_pcl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeTraversalExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeTraversalExpression) ProtoMessage() {}

func (x *ScopeTraversalExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeTraversalExpression.ProtoReflect.Descriptor instead.
func (*ScopeTraversalExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{21}
}

func (x *ScopeTraversalExpression) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *ScopeTraversalExpression) GetTraversal() *Traversal {
	if x != nil {
		return x.Traversal
	}
	return nil
}

type AnonymousFunctionExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *Expression            `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Parameters    []string               `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymousFunctionExpression) Reset() {
	*x = AnonymousFunctionExpression{}
	mi := &file_pcl_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymousFunctionExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymousFunctionExpression) ProtoMessage() {}

func (x *AnonymousFunctionExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymousFunctionExpression.ProtoReflect.Descriptor instead.
func (*AnonymousFunctionExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{22}
}

func (x *AnonymousFunctionExpression) GetBody() *Expression {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AnonymousFunctionExpression) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ConditionalExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Expression            `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	TrueExpr      *Expression            `protobuf:"bytes,2,opt,name=trueExpr,proto3" json:"trueExpr,omitempty"`
	FalseExpr     *Expression            `protobuf:"bytes,3,opt,name=falseExpr,proto3" json:"falseExpr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionalExpression) Reset() {
	*x = ConditionalExpression{}
	mi := &file_pcl_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalExpression) ProtoMessage() {}

func (x *ConditionalExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalExpression.ProtoReflect.Descriptor instead.
func (*ConditionalExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{23}
}

func (x *ConditionalExpression) GetCondition() *Expression {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *ConditionalExpression) GetTrueExpr() *Expression {
	if x != nil {
		return x.TrueExpr
	}
	return nil
}

func (x *ConditionalExpression) GetFalseExpr() *Expression {
	if x != nil {
		return x.FalseExpr
	}
	return nil
}

type BinaryOpExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=pulumipcl.Operation" json:"operation,omitempty"`
	Left          *Expression            `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expression            `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryOpExpression) Reset() {
	*x = BinaryOpExpression{}
	mi := &file_pcl_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryOpExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryOpExpression) ProtoMessage() {}

func (x *BinaryOpExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryOpExpression.ProtoReflect.Descriptor instead.
func (*BinaryOpExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{24}
}

func (x *BinaryOpExpression) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_ADD
}

func (x *BinaryOpExpression) GetLeft() *Expression {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *BinaryOpExpression) GetRight() *Expression {
	if x != nil {
		return x.Right
	}
	return nil
}

type UnaryOpExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=pulumipcl.Operation" json:"operation,omitempty"`
	Operand       *Expression            `protobuf:"bytes,2,opt,name=operand,proto3" json:"operand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryOpExpression) Reset() {
	*x = UnaryOpExpression{}
	mi := &file_pcl_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryOpExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryOpExpression) ProtoMessage() {}

func (x *UnaryOpExpression) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryOpExpression.ProtoReflect.Descriptor instead.
func (*UnaryOpExpression) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{25}
}

func (x *UnaryOpExpression) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_ADD
}

func (x *UnaryOpExpression) GetOperand() *Expression {
	if x != nil {
		return x.Operand
	}
	return nil
}

type Traversal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Each          []*Traverser           `protobuf:"bytes,1,rep,name=each,proto3" json:"each,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traversal) Reset() {
	*x = Traversal{}
	mi := &file_pcl_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traversal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traversal) ProtoMessage() {}

func (x *Traversal) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traversal.ProtoReflect.Descriptor instead.
func (*Traversal) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{26}
}

func (x *Traversal) GetEach() []*Traverser {
	if x != nil {
		return x.Each
	}
	return nil
}

type Traverser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Traverser_TraverseAttr
	//	*Traverser_TraverseIndex
	//	*Traverser_TraverseRoot
	//	*Traverser_TraverseSplat
	Value         isTraverser_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traverser) Reset() {
	*x = Traverser{}
	mi := &file_pcl_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traverser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traverser) ProtoMessage() {}

func (x *Traverser) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traverser.ProtoReflect.Descriptor instead.
func (*Traverser) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{27}
}

func (x *Traverser) GetValue() isTraverser_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Traverser) GetTraverseAttr() *TraverseAttr {
	if x != nil {
		if x, ok := x.Value.(*Traverser_TraverseAttr); ok {
			return x.TraverseAttr
		}
	}
	return nil
}

func (x *Traverser) GetTraverseIndex() *TraverseIndex {
	if x != nil {
		if x, ok := x.Value.(*Traverser_TraverseIndex); ok {
			return x.TraverseIndex
		}
	}
	return nil
}

func (x *Traverser) GetTraverseRoot() *TraverseRoot {
	if x != nil {
		if x, ok := x.Value.(*Traverser_TraverseRoot); ok {
			return x.TraverseRoot
		}
	}
	return nil
}

func (x *Traverser) GetTraverseSplat() *TraverseSplat {
	if x != nil {
		if x, ok := x.Value.(*Traverser_TraverseSplat); ok {
			return x.TraverseSplat
		}
	}
	return nil
}

type isTraverser_Value interface {
	isTraverser_Value()
}

type Traverser_TraverseAttr struct {
	TraverseAttr *TraverseAttr `protobuf:"bytes,1,opt,name=traverseAttr,proto3,oneof"`
}

type Traverser_TraverseIndex struct {
	TraverseIndex *TraverseIndex `protobuf:"bytes,2,opt,name=traverseIndex,proto3,oneof"`
}

type Traverser_TraverseRoot struct {
	TraverseRoot *TraverseRoot `protobuf:"bytes,3,opt,name=traverseRoot,proto3,oneof"`
}

type Traverser_TraverseSplat struct {
	TraverseSplat *TraverseSplat `protobuf:"bytes,4,opt,name=traverseSplat,proto3,oneof"`
}

func (*Traverser_TraverseAttr) isTraverser_Value() {}

func (*Traverser_TraverseIndex) isTraverser_Value() {}

func (*Traverser_TraverseRoot) isTraverser_Value() {}

func (*Traverser_TraverseSplat) isTraverser_Value() {}

type TraverseAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseAttr) Reset() {
	*x = TraverseAttr{}
	mi := &file_pcl_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseAttr) ProtoMessage() {}

func (x *TraverseAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseAttr.ProtoReflect.Descriptor instead.
func (*TraverseAttr) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{28}
}

func (x *TraverseAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TraverseIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TraverseIndex_IntIndex
	//	*TraverseIndex_StringIndex
	Value         isTraverseIndex_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseIndex) Reset() {
	*x = TraverseIndex{}
	mi := &file_pcl_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseIndex) ProtoMessage() {}

func (x *TraverseIndex) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseIndex.ProtoReflect.Descriptor instead.
func (*TraverseIndex) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{29}
}

func (x *TraverseIndex) GetValue() isTraverseIndex_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TraverseIndex) GetIntIndex() int64 {
	if x != nil {
		if x, ok := x.Value.(*TraverseIndex_IntIndex); ok {
			return x.IntIndex
		}
	}
	return 0
}

func (x *TraverseIndex) GetStringIndex() string {
	if x != nil {
		if x, ok := x.Value.(*TraverseIndex_StringIndex); ok {
			return x.StringIndex
		}
	}
	return ""
}

type isTraverseIndex_Value interface {
	isTraverseIndex_Value()
}

type TraverseIndex_IntIndex struct {
	IntIndex int64 `protobuf:"varint,1,opt,name=intIndex,proto3,oneof"`
}

type TraverseIndex_StringIndex struct {
	StringIndex string `protobuf:"bytes,2,opt,name=stringIndex,proto3,oneof"`
}

func (*TraverseIndex_IntIndex) isTraverseIndex_Value() {}

func (*TraverseIndex_StringIndex) isTraverseIndex_Value() {}

type TraverseRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseRoot) Reset() {
	*x = TraverseRoot{}
	mi := &file_pcl_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseRoot) ProtoMessage() {}

func (x *TraverseRoot) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseRoot.ProtoReflect.Descriptor instead.
func (*TraverseRoot) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{30}
}

func (x *TraverseRoot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TraverseSplat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Each          *Traversal             `protobuf:"bytes,1,opt,name=each,proto3" json:"each,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseSplat) Reset() {
	*x = TraverseSplat{}
	mi := &file_pcl_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseSplat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseSplat) ProtoMessage() {}

func (x *TraverseSplat) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseSplat.ProtoReflect.Descriptor instead.
func (*TraverseSplat) Descriptor() ([]byte, []int) {
	return file_pcl_proto_rawDescGZIP(), []int{31}
}

func (x *TraverseSplat) GetEach() *Traversal {
	if x != nil {
		return x.Each
	}
	return nil
}

var File_pcl_proto protoreflect.FileDescriptor

const file_pcl_proto_rawDesc = "" +
	"\n" +
	"\tpcl.proto\x12\tpulumipcl\"q\n" +
	"\x12PclProtobufProgram\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.pulumipcl.NodeR\x05nodes\x124\n" +
	"\aplugins\x18\x02 \x03(\v2\x1a.pulumipcl.PluginReferenceR\aplugins\"?\n" +
	"\x0fPluginReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x8e\x02\n" +
	"\x04Node\x121\n" +
	"\bresource\x18\x01 \x01(\v2\x13.pulumipcl.ResourceH\x00R\bresource\x12@\n" +
	"\rlocalVariable\x18\x02 \x01(\v2\x18.pulumipcl.LocalVariableH\x00R\rlocalVariable\x12C\n" +
	"\x0econfigVariable\x18\x03 \x01(\v2\x19.pulumipcl.ConfigVariableH\x00R\x0econfigVariable\x12C\n" +
	"\x0eoutputVariable\x18\x04 \x01(\v2\x19.pulumipcl.OutputVariableH\x00R\x0eoutputVariableB\a\n" +
	"\x05value\"\xcf\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vlogicalName\x18\x02 \x01(\tR\vlogicalName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.pulumipcl.ResourceInputR\x06inputs\x129\n" +
	"\aoptions\x18\x05 \x01(\v2\x1a.pulumipcl.ResourceOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"P\n" +
	"\rResourceInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\x05value\"\xf1\x03\n" +
	"\x0fResourceOptions\x128\n" +
	"\tdependsOn\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionH\x00R\tdependsOn\x88\x01\x01\x124\n" +
	"\aprotect\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionH\x01R\aprotect\x88\x01\x01\x122\n" +
	"\x06parent\x18\x03 \x01(\v2\x15.pulumipcl.ExpressionH\x02R\x06parent\x88\x01\x01\x12@\n" +
	"\rignoreChanges\x18\x04 \x01(\v2\x15.pulumipcl.ExpressionH\x03R\rignoreChanges\x88\x01\x01\x126\n" +
	"\bprovider\x18\x05 \x01(\v2\x15.pulumipcl.ExpressionH\x04R\bprovider\x88\x01\x01\x124\n" +
	"\aversion\x18\x06 \x01(\v2\x15.pulumipcl.ExpressionH\x05R\aversion\x88\x01\x01\x120\n" +
	"\x05range\x18\a \x01(\v2\x15.pulumipcl.ExpressionH\x06R\x05range\x88\x01\x01B\f\n" +
	"\n" +
	"_dependsOnB\n" +
	"\n" +
	"\b_protectB\t\n" +
	"\a_parentB\x10\n" +
	"\x0e_ignoreChangesB\v\n" +
	"\t_providerB\n" +
	"\n" +
	"\b_versionB\b\n" +
	"\x06_range\"r\n" +
	"\rLocalVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vlogicalName\x18\x02 \x01(\tR\vlogicalName\x12+\n" +
	"\x05value\x18\x03 \x01(\v2\x15.pulumipcl.ExpressionR\x05value\"\xb8\x01\n" +
	"\x0eConfigVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vlogicalName\x18\x02 \x01(\tR\vlogicalName\x125\n" +
	"\n" +
	"configType\x18\x03 \x01(\v2\x15.pulumipcl.ConfigTypeR\n" +
	"configType\x129\n" +
	"\fdefaultValue\x18\x04 \x01(\v2\x15.pulumipcl.ExpressionR\fdefaultValue\"\xc3\x02\n" +
	"\n" +
	"ConfigType\x122\n" +
	"\n" +
	"stringType\x18\x01 \x01(\v2\x10.pulumipcl.EmptyH\x00R\n" +
	"stringType\x122\n" +
	"\n" +
	"numberType\x18\x02 \x01(\v2\x10.pulumipcl.EmptyH\x00R\n" +
	"numberType\x12,\n" +
	"\aintType\x18\x03 \x01(\v2\x10.pulumipcl.EmptyH\x00R\aintType\x12.\n" +
	"\bboolType\x18\x04 \x01(\v2\x10.pulumipcl.EmptyH\x00R\bboolType\x123\n" +
	"\blistType\x18\x05 \x01(\v2\x15.pulumipcl.ConfigTypeH\x00R\blistType\x121\n" +
	"\amapType\x18\x06 \x01(\v2\x15.pulumipcl.ConfigTypeH\x00R\amapTypeB\a\n" +
	"\x05value\"s\n" +
	"\x0eOutputVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vlogicalName\x18\x02 \x01(\tR\vlogicalName\x12+\n" +
	"\x05value\x18\x03 \x01(\v2\x15.pulumipcl.ExpressionR\x05value\"\xc7\b\n" +
	"\n" +
	"Expression\x12[\n" +
	"\x16literalValueExpression\x18\x01 \x01(\v2!.pulumipcl.LiteralValueExpressionH\x00R\x16literalValueExpression\x12O\n" +
	"\x12templateExpression\x18\x02 \x01(\v2\x1d.pulumipcl.TemplateExpressionH\x00R\x12templateExpression\x12F\n" +
	"\x0findexExpression\x18\x03 \x01(\v2\x1a.pulumipcl.IndexExpressionH\x00R\x0findexExpression\x12U\n" +
	"\x14objectConsExpression\x18\x04 \x01(\v2\x1f.pulumipcl.ObjectConsExpressionH\x00R\x14objectConsExpression\x12R\n" +
	"\x13tupleConsExpression\x18\x05 \x01(\v2\x1e.pulumipcl.TupleConsExpressionH\x00R\x13tupleConsExpression\x12[\n" +
	"\x16functionCallExpression\x18\x06 \x01(\v2!.pulumipcl.FunctionCallExpressionH\x00R\x16functionCallExpression\x12j\n" +
	"\x1brelativeTraversalExpression\x18\a \x01(\v2&.pulumipcl.RelativeTraversalExpressionH\x00R\x1brelativeTraversalExpression\x12a\n" +
	"\x18scopeTraversalExpression\x18\b \x01(\v2#.pulumipcl.ScopeTraversalExpressionH\x00R\x18scopeTraversalExpression\x12j\n" +
	"\x1banonymousFunctionExpression\x18\t \x01(\v2&.pulumipcl.AnonymousFunctionExpressionH\x00R\x1banonymousFunctionExpression\x12X\n" +
	"\x15conditionalExpression\x18\n" +
	" \x01(\v2 .pulumipcl.ConditionalExpressionH\x00R\x15conditionalExpression\x12O\n" +
	"\x12binaryOpExpression\x18\v \x01(\v2\x1d.pulumipcl.BinaryOpExpressionH\x00R\x12binaryOpExpression\x12L\n" +
	"\x11unaryOpExpression\x18\f \x01(\v2\x1c.pulumipcl.UnaryOpExpressionH\x00R\x11unaryOpExpressionB\a\n" +
	"\x05value\"\xaf\x01\n" +
	"\x16LiteralValueExpression\x12$\n" +
	"\funknownValue\x18\x01 \x01(\bH\x00R\funknownValue\x12\"\n" +
	"\vstringValue\x18\x02 \x01(\tH\x00R\vstringValue\x12\"\n" +
	"\vnumberValue\x18\x03 \x01(\x01H\x00R\vnumberValue\x12\x1e\n" +
	"\tboolValue\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"A\n" +
	"\x12TemplateExpression\x12+\n" +
	"\x05parts\x18\x01 \x03(\v2\x15.pulumipcl.ExpressionR\x05parts\"q\n" +
	"\x0fIndexExpression\x125\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionR\n" +
	"collection\x12'\n" +
	"\x03key\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\x03key\"\xbd\x01\n" +
	"\x14ObjectConsExpression\x12O\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2/.pulumipcl.ObjectConsExpression.PropertiesEntryR\n" +
	"properties\x1aT\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\x05value:\x028\x01\"B\n" +
	"\x13TupleConsExpression\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.pulumipcl.ExpressionR\x05items\"a\n" +
	"\x16FunctionCallExpression\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04args\x18\x02 \x03(\v2\x1f.pulumipcl.FunctionCallArgumentR\x04args\"h\n" +
	"\x14FunctionCallArgument\x12+\n" +
	"\x05value\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionR\x05value\x12#\n" +
	"\x04type\x18\x02 \x01(\v2\x0f.pulumipcl.TypeR\x04type\"\xba\x02\n" +
	"\x04Type\x12.\n" +
	"\bboolType\x18\x01 \x01(\v2\x10.pulumipcl.EmptyH\x00R\bboolType\x12,\n" +
	"\aintType\x18\x02 \x01(\v2\x10.pulumipcl.EmptyH\x00R\aintType\x122\n" +
	"\n" +
	"numberType\x18\x03 \x01(\v2\x10.pulumipcl.EmptyH\x00R\n" +
	"numberType\x122\n" +
	"\n" +
	"stringType\x18\x04 \x01(\v2\x10.pulumipcl.EmptyH\x00R\n" +
	"stringType\x120\n" +
	"\tcomposite\x18\x05 \x01(\v2\x10.pulumipcl.EmptyH\x00R\tcomposite\x121\n" +
	"\n" +
	"outputType\x18\x06 \x01(\v2\x0f.pulumipcl.TypeH\x00R\n" +
	"outputTypeB\a\n" +
	"\x05value\"\a\n" +
	"\x05Empty\"\x80\x01\n" +
	"\x1bRelativeTraversalExpression\x12-\n" +
	"\x06source\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionR\x06source\x122\n" +
	"\ttraversal\x18\x02 \x01(\v2\x14.pulumipcl.TraversalR\ttraversal\"j\n" +
	"\x18ScopeTraversalExpression\x12\x1a\n" +
	"\brootName\x18\x01 \x01(\tR\brootName\x122\n" +
	"\ttraversal\x18\x02 \x01(\v2\x14.pulumipcl.TraversalR\ttraversal\"h\n" +
	"\x1bAnonymousFunctionExpression\x12)\n" +
	"\x04body\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionR\x04body\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\"\xb4\x01\n" +
	"\x15ConditionalExpression\x123\n" +
	"\tcondition\x18\x01 \x01(\v2\x15.pulumipcl.ExpressionR\tcondition\x121\n" +
	"\btrueExpr\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\btrueExpr\x123\n" +
	"\tfalseExpr\x18\x03 \x01(\v2\x15.pulumipcl.ExpressionR\tfalseExpr\"\xa0\x01\n" +
	"\x12BinaryOpExpression\x122\n" +
	"\toperation\x18\x01 \x01(\x0e2\x14.pulumipcl.OperationR\toperation\x12)\n" +
	"\x04left\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\x04left\x12+\n" +
	"\x05right\x18\x03 \x01(\v2\x15.pulumipcl.ExpressionR\x05right\"x\n" +
	"\x11UnaryOpExpression\x122\n" +
	"\toperation\x18\x01 \x01(\x0e2\x14.pulumipcl.OperationR\toperation\x12/\n" +
	"\aoperand\x18\x02 \x01(\v2\x15.pulumipcl.ExpressionR\aoperand\"5\n" +
	"\tTraversal\x12(\n" +
	"\x04each\x18\x01 \x03(\v2\x14.pulumipcl.TraverserR\x04each\"\x96\x02\n" +
	"\tTraverser\x12=\n" +
	"\ftraverseAttr\x18\x01 \x01(\v2\x17.pulumipcl.TraverseAttrH\x00R\ftraverseAttr\x12@\n" +
	"\rtraverseIndex\x18\x02 \x01(\v2\x18.pulumipcl.TraverseIndexH\x00R\rtraverseIndex\x12=\n" +
	"\ftraverseRoot\x18\x03 \x01(\v2\x17.pulumipcl.TraverseRootH\x00R\ftraverseRoot\x12@\n" +
	"\rtraverseSplat\x18\x04 \x01(\v2\x18.pulumipcl.TraverseSplatH\x00R\rtraverseSplatB\a\n" +
	"\x05value\"\"\n" +
	"\fTraverseAttr\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Z\n" +
	"\rTraverseIndex\x12\x1c\n" +
	"\bintIndex\x18\x01 \x01(\x03H\x00R\bintIndex\x12\"\n" +
	"\vstringIndex\x18\x02 \x01(\tH\x00R\vstringIndexB\a\n" +
	"\x05value\"\"\n" +
	"\fTraverseRoot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\rTraverseSplat\x12(\n" +
	"\x04each\x18\x01 \x01(\v2\x14.pulumipcl.TraversalR\x04each*\xd7\x01\n" +
	"\tOperation\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06DIVIDE\x10\x01\x12\t\n" +
	"\x05EQUAL\x10\x02\x12\x10\n" +
	"\fGREATER_THAN\x10\x03\x12\x19\n" +
	"\x15GREATER_THAN_OR_EQUAL\x10\x04\x12\r\n" +
	"\tLESS_THAN\x10\x05\x12\x16\n" +
	"\x12LESS_THAN_OR_EQUAL\x10\x06\x12\x0f\n" +
	"\vLOGICAL_AND\x10\a\x12\x0e\n" +
	"\n" +
	"LOGICAL_OR\x10\b\x12\n" +
	"\n" +
	"\x06MODULO\x10\t\x12\f\n" +
	"\bMULTIPLY\x10\n" +
	"\x12\r\n" +
	"\tNOT_EQUAL\x10\v\x12\f\n" +
	"\bSUBTRACT\x10\fBTZRgithub.com/andrzejressel/pulumi-rust/ast/codegen/ast/schemapcl/schemapcl;schemapclb\x06proto3"

var (
	file_pcl_proto_rawDescOnce sync.Once
	file_pcl_proto_rawDescData []byte
)

func file_pcl_proto_rawDescGZIP() []byte {
	file_pcl_proto_rawDescOnce.Do(func() {
		file_pcl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcl_proto_rawDesc), len(file_pcl_proto_rawDesc)))
	})
	return file_pcl_proto_rawDescData
}

var file_pcl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pcl_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pcl_proto_goTypes = []any{
	(Operation)(0),                      // 0: pulumipcl.Operation
	(*PclProtobufProgram)(nil),          // 1: pulumipcl.PclProtobufProgram
	(*PluginReference)(nil),             // 2: pulumipcl.PluginReference
	(*Node)(nil),                        // 3: pulumipcl.Node
	(*Resource)(nil),                    // 4: pulumipcl.Resource
	(*ResourceInput)(nil),               // 5: pulumipcl.ResourceInput
	(*ResourceOptions)(nil),             // 6: pulumipcl.ResourceOptions
	(*LocalVariable)(nil),               // 7: pulumipcl.LocalVariable
	(*ConfigVariable)(nil),              // 8: pulumipcl.ConfigVariable
	(*ConfigType)(nil),                  // 9: pulumipcl.ConfigType
	(*OutputVariable)(nil),              // 10: pulumipcl.OutputVariable
	(*Expression)(nil),                  // 11: pulumipcl.Expression
	(*LiteralValueExpression)(nil),      // 12: pulumipcl.LiteralValueExpression
	(*TemplateExpression)(nil),          // 13: pulumipcl.TemplateExpression
	(*IndexExpression)(nil),             // 14: pulumipcl.IndexExpression
	(*ObjectConsExpression)(nil),        // 15: pulumipcl.ObjectConsExpression
	(*TupleConsExpression)(nil),         // 16: pulumipcl.TupleConsExpression
	(*FunctionCallExpression)(nil),      // 17: pulumipcl.FunctionCallExpression
	(*FunctionCallArgument)(nil),        // 18: pulumipcl.FunctionCallArgument
	(*Type)(nil),                        // 19: pulumipcl.Type
	(*Empty)(nil),                       // 20: pulumipcl.Empty
	(*RelativeTraversalExpression)(nil), // 21: pulumipcl.RelativeTraversalExpression
	(*ScopeTraversalExpression)(nil),    // 22: pulumipcl.ScopeTraversalExpression
	(*AnonymousFunctionExpression)(nil), // 23: pulumipcl.AnonymousFunctionExpression
	(*ConditionalExpression)(nil),       // 24: pulumipcl.ConditionalExpression
	(*BinaryOpExpression)(nil),          // 25: pulumipcl.BinaryOpExpression
	(*UnaryOpExpression)(nil),           // 26: pulumipcl.UnaryOpExpression
	(*Traversal)(nil),                   // 27: pulumipcl.Traversal
	(*Traverser)(nil),                   // 28: pulumipcl.Traverser
	(*TraverseAttr)(nil),                // 29: pulumipcl.TraverseAttr
	(*TraverseIndex)(nil),               // 30: pulumipcl.TraverseIndex
	(*TraverseRoot)(nil),                // 31: pulumipcl.TraverseRoot
	(*TraverseSplat)(nil),               // 32: pulumipcl.TraverseSplat
	nil,                                 // 33: pulumipcl.ObjectConsExpression.PropertiesEntry
}
var file_pcl_proto_depIdxs = []int32{
	3,  // 0: pulumipcl.PclProtobufProgram.nodes:type_name -> pulumipcl.Node
	2,  // 1: pulumipcl.PclProtobufProgram.plugins:type_name -> pulumipcl.PluginReference
	4,  // 2: pulumipcl.Node.resource:type_name -> pulumipcl.Resource
	7,  // 3: pulumipcl.Node.localVariable:type_name -> pulumipcl.LocalVariable
	8,  // 4: pulumipcl.Node.configVariable:type_name -> pulumipcl.ConfigVariable
	10, // 5: pulumipcl.Node.outputVariable:type_name -> pulumipcl.OutputVariable
	5,  // 6: pulumipcl.Resource.inputs:type_name -> pulumipcl.ResourceInput
	6,  // 7: pulumipcl.Resource.options:type_name -> pulumipcl.ResourceOptions
	11, // 8: pulumipcl.ResourceInput.value:type_name -> pulumipcl.Expression
	11, // 9: pulumipcl.ResourceOptions.dependsOn:type_name -> pulumipcl.Expression
	11, // 10: pulumipcl.ResourceOptions.protect:type_name -> pulumipcl.Expression
	11, // 11: pulumipcl.ResourceOptions.parent:type_name -> pulumipcl.Expression
	11, // 12: pulumipcl.ResourceOptions.ignoreChanges:type_name -> pulumipcl.Expression
	11, // 13: pulumipcl.ResourceOptions.provider:type_name -> pulumipcl.Expression
	11, // 14: pulumipcl.ResourceOptions.version:type_name -> pulumipcl.Expression
	11, // 15: pulumipcl.ResourceOptions.range:type_name -> pulumipcl.Expression
	11, // 16: pulumipcl.LocalVariable.value:type_name -> pulumipcl.Expression
	9,  // 17: pulumipcl.ConfigVariable.configType:type_name -> pulumipcl.ConfigType
	11, // 18: pulumipcl.ConfigVariable.defaultValue:type_name -> pulumipcl.Expression
	20, // 19: pulumipcl.ConfigType.stringType:type_name -> pulumipcl.Empty
	20, // 20: pulumipcl.ConfigType.numberType:type_name -> pulumipcl.Empty
	20, // 21: pulumipcl.ConfigType.intType:type_name -> pulumipcl.Empty
	20, // 22: pulumipcl.ConfigType.boolType:type_name -> pulumipcl.Empty
	9,  // 23: pulumipcl.ConfigType.listType:type_name -> pulumipcl.ConfigType
	9,  // 24: pulumipcl.ConfigType.mapType:type_name -> pulumipcl.ConfigType
	11, // 25: pulumipcl.OutputVariable.value:type_name -> pulumipcl.Expression
	12, // 26: pulumipcl.Expression.literalValueExpression:type_name -> pulumipcl.LiteralValueExpression
	13, // 27: pulumipcl.Expression.templateExpression:type_name -> pulumipcl.TemplateExpression
	14, // 28: pulumipcl.Expression.indexExpression:type_name -> pulumipcl.IndexExpression
	15, // 29: pulumipcl.Expression.objectConsExpression:type_name -> pulumipcl.ObjectConsExpression
	16, // 30: pulumipcl.Expression.tupleConsExpression:type_name -> pulumipcl.TupleConsExpression
	17, // 31: pulumipcl.Expression.functionCallExpression:type_name -> pulumipcl.FunctionCallExpression
	21, // 32: pulumipcl.Expression.relativeTraversalExpression:type_name -> pulumipcl.RelativeTraversalExpression
	22, // 33: pulumipcl.Expression.scopeTraversalExpression:type_name -> pulumipcl.ScopeTraversalExpression
	23, // 34: pulumipcl.Expression.anonymousFunctionExpression:type_name -> pulumipcl.AnonymousFunctionExpression
	24, // 35: pulumipcl.Expression.conditionalExpression:type_name -> pulumipcl.ConditionalExpression
	25, // 36: pulumipcl.Expression.binaryOpExpression:type_name -> pulumipcl.BinaryOpExpression
	26, // 37: pulumipcl.Expression.unaryOpExpression:type_name -> pulumipcl.UnaryOpExpression
	11, // 38: pulumipcl.TemplateExpression.parts:type_name -> pulumipcl.Expression
	11, // 39: pulumipcl.IndexExpression.collection:type_name -> pulumipcl.Expression
	11, // 40: pulumipcl.IndexExpression.key:type_name -> pulumipcl.Expression
	33, // 41: pulumipcl.ObjectConsExpression.properties:type_name -> pulumipcl.ObjectConsExpression.PropertiesEntry
	11, // 42: pulumipcl.TupleConsExpression.items:type_name -> pulumipcl.Expression
	18, // 43: pulumipcl.FunctionCallExpression.args:type_name -> pulumipcl.FunctionCallArgument
	11, // 44: pulumipcl.FunctionCallArgument.value:type_name -> pulumipcl.Expression
	19, // 45: pulumipcl.FunctionCallArgument.type:type_name -> pulumipcl.Type
	20, // 46: pulumipcl.Type.boolType:type_name -> pulumipcl.Empty
	20, // 47: pulumipcl.Type.intType:type_name -> pulumipcl.Empty
	20, // 48: pulumipcl.Type.numberType:type_name -> pulumipcl.Empty
	20, // 49: pulumipcl.Type.stringType:type_name -> pulumipcl.Empty
	20, // 50: pulumipcl.Type.composite:type_name -> pulumipcl.Empty
	19, // 51: pulumipcl.Type.outputType:type_name -> pulumipcl.Type
	11, // 52: pulumipcl.RelativeTraversalExpression.source:type_name -> pulumipcl.Expression
	27, // 53: pulumipcl.RelativeTraversalExpression.traversal:type_name -> pulumipcl.Traversal
	27, // 54: pulumipcl.ScopeTraversalExpression.traversal:type_name -> pulumipcl.Traversal
	11, // 55: pulumipcl.AnonymousFunctionExpression.body:type_name -> pulumipcl.Expression
	11, // 56: pulumipcl.ConditionalExpression.condition:type_name -> pulumipcl.Expression
	11, // 57: pulumipcl.ConditionalExpression.trueExpr:type_name -> pulumipcl.Expression
	11, // 58: pulumipcl.ConditionalExpression.falseExpr:type_name -> pulumipcl.Expression
	0,  // 59: pulumipcl.BinaryOpExpression.operation:type_name -> pulumipcl.Operation
	11, // 60: pulumipcl.BinaryOpExpression.left:type_name -> pulumipcl.Expression
	11, // 61: pulumipcl.BinaryOpExpression.right:type_name -> pulumipcl.Expression
	0,  // 62: pulumipcl.UnaryOpExpression.operation:type_name -> pulumipcl.Operation
	11, // 63: pulumipcl.UnaryOpExpression.operand:type_name -> pulumipcl.Expression
	28, // 64: pulumipcl.Traversal.each:type_name -> pulumipcl.Traverser
	29, // 65: pulumipcl.Traverser.traverseAttr:type_name -> pulumipcl.TraverseAttr
	30, // 66: pulumipcl.Traverser.traverseIndex:type_name -> pulumipcl.TraverseIndex
	31, // 67: pulumipcl.Traverser.traverseRoot:type_name -> pulumipcl.TraverseRoot
	32, // 68: pulumipcl.Traverser.traverseSplat:type_name -> pulumipcl.TraverseSplat
	27, // 69: pulumipcl.TraverseSplat.each:type_name -> pulumipcl.Traversal
	11, // 70: pulumipcl.ObjectConsExpression.PropertiesEntry.value:type_name -> pulumipcl.Expression
	71, // [71:71] is the sub-list for method output_type
	71, // [71:71] is the sub-list for method input_type
	71, // [71:71] is the sub-list for extension type_name
	71, // [71:71] is the sub-list for extension extendee
	0,  // [0:71] is the sub-list for field type_name
}

func init() { file_pcl_proto_init() }
func file_pcl_proto_init() {
	if File_pcl_proto != nil {
		return
	}
	file_pcl_proto_msgTypes[2].OneofWrappers = []any{
		(*Node_Resource)(nil),
		(*Node_LocalVariable)(nil),
		(*Node_ConfigVariable)(nil),
		(*Node_OutputVariable)(nil),
	}
	file_pcl_proto_msgTypes[3].OneofWrappers = []any{}
	file_pcl_proto_msgTypes[5].OneofWrappers = []any{}
	file_pcl_proto_msgTypes[8].OneofWrappers = []any{
		(*ConfigType_StringType)(nil),
		(*ConfigType_NumberType)(nil),
		(*ConfigType_IntType)(nil),
		(*ConfigType_BoolType)(nil),
		(*ConfigType_ListType)(nil),
		(*ConfigType_MapType)(nil),
	}
	file_pcl_proto_msgTypes[10].OneofWrappers = []any{
		(*Expression_LiteralValueExpression)(nil),
		(*Expression_TemplateExpression)(nil),
		(*Expression_IndexExpression)(nil),
		(*Expression_ObjectConsExpression)(nil),
		(*Expression_TupleConsExpression)(nil),
		(*Expression_FunctionCallExpression)(nil),
		(*Expression_RelativeTraversalExpression)(nil),
		(*Expression_ScopeTraversalExpression)(nil),
		(*Expression_AnonymousFunctionExpression)(nil),
		(*Expression_ConditionalExpression)(nil),
		(*Expression_BinaryOpExpression)(nil),
		(*Expression_UnaryOpExpression)(nil),
	}
	file_pcl_proto_msgTypes[11].OneofWrappers = []any{
		(*LiteralValueExpression_UnknownValue)(nil),
		(*LiteralValueExpression_StringValue)(nil),
		(*LiteralValueExpression_NumberValue)(nil),
		(*LiteralValueExpression_BoolValue)(nil),
	}
	file_pcl_proto_msgTypes[18].OneofWrappers = []any{
		(*Type_BoolType)(nil),
		(*Type_IntType)(nil),
		(*Type_NumberType)(nil),
		(*Type_StringType)(nil),
		(*Type_Composite)(nil),
		(*Type_OutputType)(nil),
	}
	file_pcl_proto_msgTypes[27].OneofWrappers = []any{
		(*Traverser_TraverseAttr)(nil),
		(*Traverser_TraverseIndex)(nil),
		(*Traverser_TraverseRoot)(nil),
		(*Traverser_TraverseSplat)(nil),
	}
	file_pcl_proto_msgTypes[29].OneofWrappers = []any{
		(*TraverseIndex_IntIndex)(nil),
		(*TraverseIndex_StringIndex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcl_proto_rawDesc), len(file_pcl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pcl_proto_goTypes,
		DependencyIndexes: file_pcl_proto_depIdxs,
		EnumInfos:         file_pcl_proto_enumTypes,
		MessageInfos:      file_pcl_proto_msgTypes,
	}.Build()
	File_pcl_proto = out.File
	file_pcl_proto_goTypes = nil
	file_pcl_proto_depIdxs = nil
}
