// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: package.proto

package schemapackage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Package struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PluginDownloadUrl string                 `protobuf:"bytes,3,opt,name=plugin_download_url,json=pluginDownloadUrl,proto3" json:"plugin_download_url,omitempty"`
	Version           string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Resources         []*Resource            `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Functions         []*Function            `protobuf:"bytes,6,rep,name=functions,proto3" json:"functions,omitempty"`
	Types             []*GlobalType          `protobuf:"bytes,7,rep,name=types,proto3" json:"types,omitempty"`
	Provider          *Provider              `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Package) GetPluginDownloadUrl() string {
	if x != nil {
		return x.PluginDownloadUrl
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Package) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Package) GetTypes() []*GlobalType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Package) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type Provider struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Description      string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	InputProperties  []*InputProperty       `protobuf:"bytes,2,rep,name=input_properties,json=inputProperties,proto3" json:"input_properties,omitempty"`
	OutputProperties []*OutputProperty      `protobuf:"bytes,3,rep,name=output_properties,json=outputProperties,proto3" json:"output_properties,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Provider) GetInputProperties() []*InputProperty {
	if x != nil {
		return x.InputProperties
	}
	return nil
}

func (x *Provider) GetOutputProperties() []*OutputProperty {
	if x != nil {
		return x.OutputProperties
	}
	return nil
}

type Resource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ElementId        *ElementId             `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputProperties  []*InputProperty       `protobuf:"bytes,3,rep,name=input_properties,json=inputProperties,proto3" json:"input_properties,omitempty"`
	OutputProperties []*OutputProperty      `protobuf:"bytes,4,rep,name=output_properties,json=outputProperties,proto3" json:"output_properties,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetElementId() *ElementId {
	if x != nil {
		return x.ElementId
	}
	return nil
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetInputProperties() []*InputProperty {
	if x != nil {
		return x.InputProperties
	}
	return nil
}

func (x *Resource) GetOutputProperties() []*OutputProperty {
	if x != nil {
		return x.OutputProperties
	}
	return nil
}

type Function struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ElementId        *ElementId             `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputProperties  []*InputProperty       `protobuf:"bytes,3,rep,name=input_properties,json=inputProperties,proto3" json:"input_properties,omitempty"`
	OutputProperties []*OutputProperty      `protobuf:"bytes,4,rep,name=output_properties,json=outputProperties,proto3" json:"output_properties,omitempty"`
	ReturnType       *Type                  `protobuf:"bytes,5,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_package_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{3}
}

func (x *Function) GetElementId() *ElementId {
	if x != nil {
		return x.ElementId
	}
	return nil
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Function) GetInputProperties() []*InputProperty {
	if x != nil {
		return x.InputProperties
	}
	return nil
}

func (x *Function) GetOutputProperties() []*OutputProperty {
	if x != nil {
		return x.OutputProperties
	}
	return nil
}

func (x *Function) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

type ElementId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     []string               `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Raw           string                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementId) Reset() {
	*x = ElementId{}
	mi := &file_package_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementId) ProtoMessage() {}

func (x *ElementId) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementId.ProtoReflect.Descriptor instead.
func (*ElementId) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{4}
}

func (x *ElementId) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ElementId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ElementId) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type InputProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputProperty) Reset() {
	*x = InputProperty{}
	mi := &file_package_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputProperty) ProtoMessage() {}

func (x *InputProperty) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputProperty.ProtoReflect.Descriptor instead.
func (*InputProperty) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{5}
}

func (x *InputProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputProperty) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *InputProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OutputProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputProperty) Reset() {
	*x = OutputProperty{}
	mi := &file_package_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputProperty) ProtoMessage() {}

func (x *OutputProperty) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputProperty.ProtoReflect.Descriptor instead.
func (*OutputProperty) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{6}
}

func (x *OutputProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputProperty) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *OutputProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypeValue:
	//
	//	*Type_BoolType
	//	*Type_IntType
	//	*Type_NumberType
	//	*Type_StringType
	//	*Type_ArrayType
	//	*Type_MapType
	//	*Type_RefType
	//	*Type_OptionalType
	//	*Type_UnionType
	//	*Type_ConstString
	TypeValue     isType_TypeValue `protobuf_oneof:"type_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_package_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{7}
}

func (x *Type) GetTypeValue() isType_TypeValue {
	if x != nil {
		return x.TypeValue
	}
	return nil
}

func (x *Type) GetBoolType() *Empty {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_BoolType); ok {
			return x.BoolType
		}
	}
	return nil
}

func (x *Type) GetIntType() *Empty {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_IntType); ok {
			return x.IntType
		}
	}
	return nil
}

func (x *Type) GetNumberType() *Empty {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_NumberType); ok {
			return x.NumberType
		}
	}
	return nil
}

func (x *Type) GetStringType() *Empty {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_StringType); ok {
			return x.StringType
		}
	}
	return nil
}

func (x *Type) GetArrayType() *Type {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_ArrayType); ok {
			return x.ArrayType
		}
	}
	return nil
}

func (x *Type) GetMapType() *Type {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_MapType); ok {
			return x.MapType
		}
	}
	return nil
}

func (x *Type) GetRefType() *RefType {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_RefType); ok {
			return x.RefType
		}
	}
	return nil
}

func (x *Type) GetOptionalType() *Type {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_OptionalType); ok {
			return x.OptionalType
		}
	}
	return nil
}

func (x *Type) GetUnionType() *DiscriminatedUnion {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_UnionType); ok {
			return x.UnionType
		}
	}
	return nil
}

func (x *Type) GetConstString() string {
	if x != nil {
		if x, ok := x.TypeValue.(*Type_ConstString); ok {
			return x.ConstString
		}
	}
	return ""
}

type isType_TypeValue interface {
	isType_TypeValue()
}

type Type_BoolType struct {
	BoolType *Empty `protobuf:"bytes,1,opt,name=bool_type,json=boolType,proto3,oneof"`
}

type Type_IntType struct {
	IntType *Empty `protobuf:"bytes,2,opt,name=int_type,json=intType,proto3,oneof"`
}

type Type_NumberType struct {
	NumberType *Empty `protobuf:"bytes,3,opt,name=number_type,json=numberType,proto3,oneof"`
}

type Type_StringType struct {
	StringType *Empty `protobuf:"bytes,4,opt,name=string_type,json=stringType,proto3,oneof"`
}

type Type_ArrayType struct {
	ArrayType *Type `protobuf:"bytes,5,opt,name=array_type,json=arrayType,proto3,oneof"`
}

type Type_MapType struct {
	MapType *Type `protobuf:"bytes,6,opt,name=map_type,json=mapType,proto3,oneof"`
}

type Type_RefType struct {
	RefType *RefType `protobuf:"bytes,7,opt,name=ref_type,json=refType,proto3,oneof"`
}

type Type_OptionalType struct {
	OptionalType *Type `protobuf:"bytes,8,opt,name=optional_type,json=optionalType,proto3,oneof"`
}

type Type_UnionType struct {
	UnionType *DiscriminatedUnion `protobuf:"bytes,9,opt,name=union_type,json=unionType,proto3,oneof"`
}

type Type_ConstString struct {
	ConstString string `protobuf:"bytes,10,opt,name=const_string,json=constString,proto3,oneof"`
}

func (*Type_BoolType) isType_TypeValue() {}

func (*Type_IntType) isType_TypeValue() {}

func (*Type_NumberType) isType_TypeValue() {}

func (*Type_StringType) isType_TypeValue() {}

func (*Type_ArrayType) isType_TypeValue() {}

func (*Type_MapType) isType_TypeValue() {}

func (*Type_RefType) isType_TypeValue() {}

func (*Type_OptionalType) isType_TypeValue() {}

func (*Type_UnionType) isType_TypeValue() {}

func (*Type_ConstString) isType_TypeValue() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_package_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{8}
}

type RefType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RefValue:
	//
	//	*RefType_TypeRef
	//	*RefType_Archive
	//	*RefType_Asset
	//	*RefType_Any
	//	*RefType_CurrentProvider
	RefValue      isRefType_RefValue `protobuf_oneof:"ref_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefType) Reset() {
	*x = RefType{}
	mi := &file_package_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefType) ProtoMessage() {}

func (x *RefType) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefType.ProtoReflect.Descriptor instead.
func (*RefType) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{9}
}

func (x *RefType) GetRefValue() isRefType_RefValue {
	if x != nil {
		return x.RefValue
	}
	return nil
}

func (x *RefType) GetTypeRef() *ElementId {
	if x != nil {
		if x, ok := x.RefValue.(*RefType_TypeRef); ok {
			return x.TypeRef
		}
	}
	return nil
}

func (x *RefType) GetArchive() *Empty {
	if x != nil {
		if x, ok := x.RefValue.(*RefType_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *RefType) GetAsset() *Empty {
	if x != nil {
		if x, ok := x.RefValue.(*RefType_Asset); ok {
			return x.Asset
		}
	}
	return nil
}

func (x *RefType) GetAny() *Empty {
	if x != nil {
		if x, ok := x.RefValue.(*RefType_Any); ok {
			return x.Any
		}
	}
	return nil
}

func (x *RefType) GetCurrentProvider() *Empty {
	if x != nil {
		if x, ok := x.RefValue.(*RefType_CurrentProvider); ok {
			return x.CurrentProvider
		}
	}
	return nil
}

type isRefType_RefValue interface {
	isRefType_RefValue()
}

type RefType_TypeRef struct {
	TypeRef *ElementId `protobuf:"bytes,1,opt,name=type_ref,json=typeRef,proto3,oneof"`
}

type RefType_Archive struct {
	Archive *Empty `protobuf:"bytes,2,opt,name=archive,proto3,oneof"`
}

type RefType_Asset struct {
	Asset *Empty `protobuf:"bytes,3,opt,name=asset,proto3,oneof"`
}

type RefType_Any struct {
	Any *Empty `protobuf:"bytes,4,opt,name=any,proto3,oneof"`
}

type RefType_CurrentProvider struct {
	CurrentProvider *Empty `protobuf:"bytes,5,opt,name=current_provider,json=currentProvider,proto3,oneof"`
}

func (*RefType_TypeRef) isRefType_RefValue() {}

func (*RefType_Archive) isRefType_RefValue() {}

func (*RefType_Asset) isRefType_RefValue() {}

func (*RefType_Any) isRefType_RefValue() {}

func (*RefType_CurrentProvider) isRefType_RefValue() {}

type DiscriminatedUnion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*Type                `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	DefaultType   *Type                  `protobuf:"bytes,2,opt,name=default_type,json=defaultType,proto3" json:"default_type,omitempty"`
	Discriminator string                 `protobuf:"bytes,3,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	Mapping       map[string]string      `protobuf:"bytes,4,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscriminatedUnion) Reset() {
	*x = DiscriminatedUnion{}
	mi := &file_package_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscriminatedUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscriminatedUnion) ProtoMessage() {}

func (x *DiscriminatedUnion) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscriminatedUnion.ProtoReflect.Descriptor instead.
func (*DiscriminatedUnion) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{10}
}

func (x *DiscriminatedUnion) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *DiscriminatedUnion) GetDefaultType() *Type {
	if x != nil {
		return x.DefaultType
	}
	return nil
}

func (x *DiscriminatedUnion) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *DiscriminatedUnion) GetMapping() map[string]string {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type GlobalType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ElementId       *ElementId             `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	GlobalTypeValue *GlobalTypeValue       `protobuf:"bytes,2,opt,name=global_type_value,json=globalTypeValue,proto3" json:"global_type_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalType) Reset() {
	*x = GlobalType{}
	mi := &file_package_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalType) ProtoMessage() {}

func (x *GlobalType) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalType.ProtoReflect.Descriptor instead.
func (*GlobalType) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalType) GetElementId() *ElementId {
	if x != nil {
		return x.ElementId
	}
	return nil
}

func (x *GlobalType) GetGlobalTypeValue() *GlobalTypeValue {
	if x != nil {
		return x.GlobalTypeValue
	}
	return nil
}

type GlobalTypeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GlobalTypeValue_Object
	//	*GlobalTypeValue_StringEnum
	//	*GlobalTypeValue_NumberEnum
	//	*GlobalTypeValue_IntegerEnum
	Value         isGlobalTypeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalTypeValue) Reset() {
	*x = GlobalTypeValue{}
	mi := &file_package_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalTypeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalTypeValue) ProtoMessage() {}

func (x *GlobalTypeValue) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalTypeValue.ProtoReflect.Descriptor instead.
func (*GlobalTypeValue) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{12}
}

func (x *GlobalTypeValue) GetValue() isGlobalTypeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GlobalTypeValue) GetObject() *ObjectType {
	if x != nil {
		if x, ok := x.Value.(*GlobalTypeValue_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *GlobalTypeValue) GetStringEnum() *StringEnum {
	if x != nil {
		if x, ok := x.Value.(*GlobalTypeValue_StringEnum); ok {
			return x.StringEnum
		}
	}
	return nil
}

func (x *GlobalTypeValue) GetNumberEnum() *NumberEnum {
	if x != nil {
		if x, ok := x.Value.(*GlobalTypeValue_NumberEnum); ok {
			return x.NumberEnum
		}
	}
	return nil
}

func (x *GlobalTypeValue) GetIntegerEnum() *IntegerEnum {
	if x != nil {
		if x, ok := x.Value.(*GlobalTypeValue_IntegerEnum); ok {
			return x.IntegerEnum
		}
	}
	return nil
}

type isGlobalTypeValue_Value interface {
	isGlobalTypeValue_Value()
}

type GlobalTypeValue_Object struct {
	Object *ObjectType `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type GlobalTypeValue_StringEnum struct {
	StringEnum *StringEnum `protobuf:"bytes,2,opt,name=string_enum,json=stringEnum,proto3,oneof"`
}

type GlobalTypeValue_NumberEnum struct {
	NumberEnum *NumberEnum `protobuf:"bytes,3,opt,name=number_enum,json=numberEnum,proto3,oneof"`
}

type GlobalTypeValue_IntegerEnum struct {
	IntegerEnum *IntegerEnum `protobuf:"bytes,4,opt,name=integer_enum,json=integerEnum,proto3,oneof"`
}

func (*GlobalTypeValue_Object) isGlobalTypeValue_Value() {}

func (*GlobalTypeValue_StringEnum) isGlobalTypeValue_Value() {}

func (*GlobalTypeValue_NumberEnum) isGlobalTypeValue_Value() {}

func (*GlobalTypeValue_IntegerEnum) isGlobalTypeValue_Value() {}

type ObjectType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Properties    []*GlobalTypeProperty  `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectType) Reset() {
	*x = ObjectType{}
	mi := &file_package_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectType) ProtoMessage() {}

func (x *ObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectType.ProtoReflect.Descriptor instead.
func (*ObjectType) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{13}
}

func (x *ObjectType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObjectType) GetProperties() []*GlobalTypeProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type StringEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Elements      []*StringEnumElement   `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEnum) Reset() {
	*x = StringEnum{}
	mi := &file_package_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEnum) ProtoMessage() {}

func (x *StringEnum) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEnum.ProtoReflect.Descriptor instead.
func (*StringEnum) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{14}
}

func (x *StringEnum) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StringEnum) GetElements() []*StringEnumElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type NumberEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Elements      []*NumberEnumElement   `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberEnum) Reset() {
	*x = NumberEnum{}
	mi := &file_package_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberEnum) ProtoMessage() {}

func (x *NumberEnum) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberEnum.ProtoReflect.Descriptor instead.
func (*NumberEnum) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{15}
}

func (x *NumberEnum) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NumberEnum) GetElements() []*NumberEnumElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type IntegerEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Elements      []*IntegerEnumElement  `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerEnum) Reset() {
	*x = IntegerEnum{}
	mi := &file_package_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerEnum) ProtoMessage() {}

func (x *IntegerEnum) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerEnum.ProtoReflect.Descriptor instead.
func (*IntegerEnum) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{16}
}

func (x *IntegerEnum) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntegerEnum) GetElements() []*IntegerEnumElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type GlobalTypeProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalTypeProperty) Reset() {
	*x = GlobalTypeProperty{}
	mi := &file_package_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalTypeProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalTypeProperty) ProtoMessage() {}

func (x *GlobalTypeProperty) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalTypeProperty.ProtoReflect.Descriptor instead.
func (*GlobalTypeProperty) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{17}
}

func (x *GlobalTypeProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlobalTypeProperty) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GlobalTypeProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StringEnumElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEnumElement) Reset() {
	*x = StringEnumElement{}
	mi := &file_package_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEnumElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEnumElement) ProtoMessage() {}

func (x *StringEnumElement) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEnumElement.ProtoReflect.Descriptor instead.
func (*StringEnumElement) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{18}
}

func (x *StringEnumElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StringEnumElement) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringEnumElement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type NumberEnumElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberEnumElement) Reset() {
	*x = NumberEnumElement{}
	mi := &file_package_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberEnumElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberEnumElement) ProtoMessage() {}

func (x *NumberEnumElement) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberEnumElement.ProtoReflect.Descriptor instead.
func (*NumberEnumElement) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{19}
}

func (x *NumberEnumElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NumberEnumElement) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumberEnumElement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type IntegerEnumElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerEnumElement) Reset() {
	*x = IntegerEnumElement{}
	mi := &file_package_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerEnumElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerEnumElement) ProtoMessage() {}

func (x *IntegerEnumElement) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerEnumElement.ProtoReflect.Descriptor instead.
func (*IntegerEnumElement) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{20}
}

func (x *IntegerEnumElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntegerEnumElement) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntegerEnumElement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_package_proto protoreflect.FileDescriptor

const file_package_proto_rawDesc = "" +
	"\n" +
	"\rpackage.proto\x12\rpulumipackage\"\xde\x02\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12.\n" +
	"\x13plugin_download_url\x18\x03 \x01(\tR\x11pluginDownloadUrl\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x125\n" +
	"\tresources\x18\x05 \x03(\v2\x17.pulumipackage.ResourceR\tresources\x125\n" +
	"\tfunctions\x18\x06 \x03(\v2\x17.pulumipackage.FunctionR\tfunctions\x12/\n" +
	"\x05types\x18\a \x03(\v2\x19.pulumipackage.GlobalTypeR\x05types\x123\n" +
	"\bprovider\x18\b \x01(\v2\x17.pulumipackage.ProviderR\bprovider\"\xc1\x01\n" +
	"\bProvider\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12G\n" +
	"\x10input_properties\x18\x02 \x03(\v2\x1c.pulumipackage.InputPropertyR\x0finputProperties\x12J\n" +
	"\x11output_properties\x18\x03 \x03(\v2\x1d.pulumipackage.OutputPropertyR\x10outputProperties\"\xfa\x01\n" +
	"\bResource\x127\n" +
	"\n" +
	"element_id\x18\x01 \x01(\v2\x18.pulumipackage.ElementIdR\telementId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\x10input_properties\x18\x03 \x03(\v2\x1c.pulumipackage.InputPropertyR\x0finputProperties\x12J\n" +
	"\x11output_properties\x18\x04 \x03(\v2\x1d.pulumipackage.OutputPropertyR\x10outputProperties\"\xb0\x02\n" +
	"\bFunction\x127\n" +
	"\n" +
	"element_id\x18\x01 \x01(\v2\x18.pulumipackage.ElementIdR\telementId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\x10input_properties\x18\x03 \x03(\v2\x1c.pulumipackage.InputPropertyR\x0finputProperties\x12J\n" +
	"\x11output_properties\x18\x04 \x03(\v2\x1d.pulumipackage.OutputPropertyR\x10outputProperties\x124\n" +
	"\vreturn_type\x18\x05 \x01(\v2\x13.pulumipackage.TypeR\n" +
	"returnType\"O\n" +
	"\tElementId\x12\x1c\n" +
	"\tnamespace\x18\x01 \x03(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\"n\n" +
	"\rInputProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.pulumipackage.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"o\n" +
	"\x0eOutputProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.pulumipackage.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb0\x04\n" +
	"\x04Type\x123\n" +
	"\tbool_type\x18\x01 \x01(\v2\x14.pulumipackage.EmptyH\x00R\bboolType\x121\n" +
	"\bint_type\x18\x02 \x01(\v2\x14.pulumipackage.EmptyH\x00R\aintType\x127\n" +
	"\vnumber_type\x18\x03 \x01(\v2\x14.pulumipackage.EmptyH\x00R\n" +
	"numberType\x127\n" +
	"\vstring_type\x18\x04 \x01(\v2\x14.pulumipackage.EmptyH\x00R\n" +
	"stringType\x124\n" +
	"\n" +
	"array_type\x18\x05 \x01(\v2\x13.pulumipackage.TypeH\x00R\tarrayType\x120\n" +
	"\bmap_type\x18\x06 \x01(\v2\x13.pulumipackage.TypeH\x00R\amapType\x123\n" +
	"\bref_type\x18\a \x01(\v2\x16.pulumipackage.RefTypeH\x00R\arefType\x12:\n" +
	"\roptional_type\x18\b \x01(\v2\x13.pulumipackage.TypeH\x00R\foptionalType\x12B\n" +
	"\n" +
	"union_type\x18\t \x01(\v2!.pulumipackage.DiscriminatedUnionH\x00R\tunionType\x12#\n" +
	"\fconst_string\x18\n" +
	" \x01(\tH\x00R\vconstStringB\f\n" +
	"\n" +
	"type_value\"\a\n" +
	"\x05Empty\"\x9a\x02\n" +
	"\aRefType\x125\n" +
	"\btype_ref\x18\x01 \x01(\v2\x18.pulumipackage.ElementIdH\x00R\atypeRef\x120\n" +
	"\aarchive\x18\x02 \x01(\v2\x14.pulumipackage.EmptyH\x00R\aarchive\x12,\n" +
	"\x05asset\x18\x03 \x01(\v2\x14.pulumipackage.EmptyH\x00R\x05asset\x12(\n" +
	"\x03any\x18\x04 \x01(\v2\x14.pulumipackage.EmptyH\x00R\x03any\x12A\n" +
	"\x10current_provider\x18\x05 \x01(\v2\x14.pulumipackage.EmptyH\x00R\x0fcurrentProviderB\v\n" +
	"\tref_value\"\xa3\x02\n" +
	"\x12DiscriminatedUnion\x12)\n" +
	"\x05types\x18\x01 \x03(\v2\x13.pulumipackage.TypeR\x05types\x126\n" +
	"\fdefault_type\x18\x02 \x01(\v2\x13.pulumipackage.TypeR\vdefaultType\x12$\n" +
	"\rdiscriminator\x18\x03 \x01(\tR\rdiscriminator\x12H\n" +
	"\amapping\x18\x04 \x03(\v2..pulumipackage.DiscriminatedUnion.MappingEntryR\amapping\x1a:\n" +
	"\fMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\n" +
	"GlobalType\x127\n" +
	"\n" +
	"element_id\x18\x01 \x01(\v2\x18.pulumipackage.ElementIdR\telementId\x12J\n" +
	"\x11global_type_value\x18\x02 \x01(\v2\x1e.pulumipackage.GlobalTypeValueR\x0fglobalTypeValue\"\x8c\x02\n" +
	"\x0fGlobalTypeValue\x123\n" +
	"\x06object\x18\x01 \x01(\v2\x19.pulumipackage.ObjectTypeH\x00R\x06object\x12<\n" +
	"\vstring_enum\x18\x02 \x01(\v2\x19.pulumipackage.StringEnumH\x00R\n" +
	"stringEnum\x12<\n" +
	"\vnumber_enum\x18\x03 \x01(\v2\x19.pulumipackage.NumberEnumH\x00R\n" +
	"numberEnum\x12?\n" +
	"\finteger_enum\x18\x04 \x01(\v2\x1a.pulumipackage.IntegerEnumH\x00R\vintegerEnumB\a\n" +
	"\x05value\"q\n" +
	"\n" +
	"ObjectType\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12A\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2!.pulumipackage.GlobalTypePropertyR\n" +
	"properties\"l\n" +
	"\n" +
	"StringEnum\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12<\n" +
	"\belements\x18\x02 \x03(\v2 .pulumipackage.StringEnumElementR\belements\"l\n" +
	"\n" +
	"NumberEnum\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12<\n" +
	"\belements\x18\x02 \x03(\v2 .pulumipackage.NumberEnumElementR\belements\"n\n" +
	"\vIntegerEnum\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12=\n" +
	"\belements\x18\x02 \x03(\v2!.pulumipackage.IntegerEnumElementR\belements\"s\n" +
	"\x12GlobalTypeProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.pulumipackage.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"_\n" +
	"\x11StringEnumElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"_\n" +
	"\x11NumberEnumElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"`\n" +
	"\x12IntegerEnumElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB`Z^github.com/andrzejressel/pulumi-rust/ast/codegen/ast/schemapackage/schemapackage;schemapackageb\x06proto3"

var (
	file_package_proto_rawDescOnce sync.Once
	file_package_proto_rawDescData []byte
)

func file_package_proto_rawDescGZIP() []byte {
	file_package_proto_rawDescOnce.Do(func() {
		file_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)))
	})
	return file_package_proto_rawDescData
}

var file_package_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_package_proto_goTypes = []any{
	(*Package)(nil),            // 0: pulumipackage.Package
	(*Provider)(nil),           // 1: pulumipackage.Provider
	(*Resource)(nil),           // 2: pulumipackage.Resource
	(*Function)(nil),           // 3: pulumipackage.Function
	(*ElementId)(nil),          // 4: pulumipackage.ElementId
	(*InputProperty)(nil),      // 5: pulumipackage.InputProperty
	(*OutputProperty)(nil),     // 6: pulumipackage.OutputProperty
	(*Type)(nil),               // 7: pulumipackage.Type
	(*Empty)(nil),              // 8: pulumipackage.Empty
	(*RefType)(nil),            // 9: pulumipackage.RefType
	(*DiscriminatedUnion)(nil), // 10: pulumipackage.DiscriminatedUnion
	(*GlobalType)(nil),         // 11: pulumipackage.GlobalType
	(*GlobalTypeValue)(nil),    // 12: pulumipackage.GlobalTypeValue
	(*ObjectType)(nil),         // 13: pulumipackage.ObjectType
	(*StringEnum)(nil),         // 14: pulumipackage.StringEnum
	(*NumberEnum)(nil),         // 15: pulumipackage.NumberEnum
	(*IntegerEnum)(nil),        // 16: pulumipackage.IntegerEnum
	(*GlobalTypeProperty)(nil), // 17: pulumipackage.GlobalTypeProperty
	(*StringEnumElement)(nil),  // 18: pulumipackage.StringEnumElement
	(*NumberEnumElement)(nil),  // 19: pulumipackage.NumberEnumElement
	(*IntegerEnumElement)(nil), // 20: pulumipackage.IntegerEnumElement
	nil,                        // 21: pulumipackage.DiscriminatedUnion.MappingEntry
}
var file_package_proto_depIdxs = []int32{
	2,  // 0: pulumipackage.Package.resources:type_name -> pulumipackage.Resource
	3,  // 1: pulumipackage.Package.functions:type_name -> pulumipackage.Function
	11, // 2: pulumipackage.Package.types:type_name -> pulumipackage.GlobalType
	1,  // 3: pulumipackage.Package.provider:type_name -> pulumipackage.Provider
	5,  // 4: pulumipackage.Provider.input_properties:type_name -> pulumipackage.InputProperty
	6,  // 5: pulumipackage.Provider.output_properties:type_name -> pulumipackage.OutputProperty
	4,  // 6: pulumipackage.Resource.element_id:type_name -> pulumipackage.ElementId
	5,  // 7: pulumipackage.Resource.input_properties:type_name -> pulumipackage.InputProperty
	6,  // 8: pulumipackage.Resource.output_properties:type_name -> pulumipackage.OutputProperty
	4,  // 9: pulumipackage.Function.element_id:type_name -> pulumipackage.ElementId
	5,  // 10: pulumipackage.Function.input_properties:type_name -> pulumipackage.InputProperty
	6,  // 11: pulumipackage.Function.output_properties:type_name -> pulumipackage.OutputProperty
	7,  // 12: pulumipackage.Function.return_type:type_name -> pulumipackage.Type
	7,  // 13: pulumipackage.InputProperty.type:type_name -> pulumipackage.Type
	7,  // 14: pulumipackage.OutputProperty.type:type_name -> pulumipackage.Type
	8,  // 15: pulumipackage.Type.bool_type:type_name -> pulumipackage.Empty
	8,  // 16: pulumipackage.Type.int_type:type_name -> pulumipackage.Empty
	8,  // 17: pulumipackage.Type.number_type:type_name -> pulumipackage.Empty
	8,  // 18: pulumipackage.Type.string_type:type_name -> pulumipackage.Empty
	7,  // 19: pulumipackage.Type.array_type:type_name -> pulumipackage.Type
	7,  // 20: pulumipackage.Type.map_type:type_name -> pulumipackage.Type
	9,  // 21: pulumipackage.Type.ref_type:type_name -> pulumipackage.RefType
	7,  // 22: pulumipackage.Type.optional_type:type_name -> pulumipackage.Type
	10, // 23: pulumipackage.Type.union_type:type_name -> pulumipackage.DiscriminatedUnion
	4,  // 24: pulumipackage.RefType.type_ref:type_name -> pulumipackage.ElementId
	8,  // 25: pulumipackage.RefType.archive:type_name -> pulumipackage.Empty
	8,  // 26: pulumipackage.RefType.asset:type_name -> pulumipackage.Empty
	8,  // 27: pulumipackage.RefType.any:type_name -> pulumipackage.Empty
	8,  // 28: pulumipackage.RefType.current_provider:type_name -> pulumipackage.Empty
	7,  // 29: pulumipackage.DiscriminatedUnion.types:type_name -> pulumipackage.Type
	7,  // 30: pulumipackage.DiscriminatedUnion.default_type:type_name -> pulumipackage.Type
	21, // 31: pulumipackage.DiscriminatedUnion.mapping:type_name -> pulumipackage.DiscriminatedUnion.MappingEntry
	4,  // 32: pulumipackage.GlobalType.element_id:type_name -> pulumipackage.ElementId
	12, // 33: pulumipackage.GlobalType.global_type_value:type_name -> pulumipackage.GlobalTypeValue
	13, // 34: pulumipackage.GlobalTypeValue.object:type_name -> pulumipackage.ObjectType
	14, // 35: pulumipackage.GlobalTypeValue.string_enum:type_name -> pulumipackage.StringEnum
	15, // 36: pulumipackage.GlobalTypeValue.number_enum:type_name -> pulumipackage.NumberEnum
	16, // 37: pulumipackage.GlobalTypeValue.integer_enum:type_name -> pulumipackage.IntegerEnum
	17, // 38: pulumipackage.ObjectType.properties:type_name -> pulumipackage.GlobalTypeProperty
	18, // 39: pulumipackage.StringEnum.elements:type_name -> pulumipackage.StringEnumElement
	19, // 40: pulumipackage.NumberEnum.elements:type_name -> pulumipackage.NumberEnumElement
	20, // 41: pulumipackage.IntegerEnum.elements:type_name -> pulumipackage.IntegerEnumElement
	7,  // 42: pulumipackage.GlobalTypeProperty.type:type_name -> pulumipackage.Type
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_package_proto_init() }
func file_package_proto_init() {
	if File_package_proto != nil {
		return
	}
	file_package_proto_msgTypes[7].OneofWrappers = []any{
		(*Type_BoolType)(nil),
		(*Type_IntType)(nil),
		(*Type_NumberType)(nil),
		(*Type_StringType)(nil),
		(*Type_ArrayType)(nil),
		(*Type_MapType)(nil),
		(*Type_RefType)(nil),
		(*Type_OptionalType)(nil),
		(*Type_UnionType)(nil),
		(*Type_ConstString)(nil),
	}
	file_package_proto_msgTypes[9].OneofWrappers = []any{
		(*RefType_TypeRef)(nil),
		(*RefType_Archive)(nil),
		(*RefType_Asset)(nil),
		(*RefType_Any)(nil),
		(*RefType_CurrentProvider)(nil),
	}
	file_package_proto_msgTypes[12].OneofWrappers = []any{
		(*GlobalTypeValue_Object)(nil),
		(*GlobalTypeValue_StringEnum)(nil),
		(*GlobalTypeValue_NumberEnum)(nil),
		(*GlobalTypeValue_IntegerEnum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_proto_goTypes,
		DependencyIndexes: file_package_proto_depIdxs,
		MessageInfos:      file_package_proto_msgTypes,
	}.Build()
	File_package_proto = out.File
	file_package_proto_goTypes = nil
	file_package_proto_depIdxs = nil
}
