set windows-shell := ["pwsh.exe", "-c"]

gen:
    protoc --proto_path=. --go_out=protobuf/schemapcl --go_opt=paths=source_relative pcl.proto
    protoc --proto_path=. --go_out=protobuf/schemapackage --go_opt=paths=source_relative package.proto

fmt:
    go fmt ./...

test:
    go test -v -count=1 ./...

regenerate-test $PULUMI_ACCEPT="1":
    go test -v -count=1 ./...
